# Generated by Django 3.0.8 on 2020-07-29 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kintaiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tprojectmembers',
            table='t_project_members',
        ),
    ]
